#!/bin/bash

if ! [ -t 0 ]; then
	read -a ref
fi

echo "running"

IFS='/' read -ra REF <<< "${ref[2]}"
branch="${REF[2]}"

if [ $branch == "main" ]; then
	crumb=$(curl -u "adiln22:$my_pass" -s 'http://my-jenkins-cicd:8080/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb)')
	curl -u "adiln22:$my_pass" -H "$crumb" -X POST http://my-jenkins-cicd:8080/job/react-pipeline/build?delay=0sec

	if [ $? -eq 0 ]; then
		echo "*** Ok"
	else
		echo "*** Error"
	fi

fi

